"""
Generate revision tasks for each unique test screen and taxonomy category,
using a specified backend.

Unique screens are determined by the case study number extracted from meta.json
source_folder (regex CaseStudy-(\\d+)). For each unique screen × 7 taxonomy
categories, 3 tasks are generated by default.

Usage:
    python Testing/RevisionGenerator/run.py --backend gemini
    python Testing/RevisionGenerator/run.py --backend vertexai --run-name finetuned-v1
    python Testing/RevisionGenerator/run.py --backend gemini --resume
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

_ROOT = Path(__file__).parent.parent.parent
load_dotenv(_ROOT / "Util" / ".env")

sys.path.insert(0, str(_ROOT / "Util"))
sys.path.insert(0, str(_ROOT / "RevisionGeneration"))

from backends import get_backend
from generate_core import generate_tasks

_TEST_DATASET = _ROOT / "Datasets" / "RevisionGeneratorModelDataset" / "Test"
_RAW_DATASET  = _ROOT / "Datasets" / "RawDataset"
_TAXONOMY     = _ROOT / "Taxonomy" / "RevisionTaxonomy" / "Results" / "taxonomy.json"
_RESULTS_DIR  = Path(__file__).parent / "Results"

_CASE_STUDY_RE = re.compile(r"CaseStudy-(\d+)")


def _load_taxonomy() -> list[dict]:
    return json.loads(_TAXONOMY.read_text())["categories"]


def _unique_screens(test_dir: Path) -> dict[str, dict]:
    """Return {case_study_number: {example_key, source_folder}} for unique screens.

    Deduplicates by the integer case study number (before the dot in CaseStudy-X.Y).
    When multiple examples share a case study number, the first (sorted) wins.
    """
    screens: dict[str, dict] = {}
    for example_dir in sorted(test_dir.iterdir()):
        if not example_dir.is_dir():
            continue
        meta_file = example_dir / "meta.json"
        if not meta_file.exists():
            continue
        meta = json.loads(meta_file.read_text())
        source_folder = meta.get("source_folder", "")
        m = _CASE_STUDY_RE.search(source_folder)
        if not m:
            continue
        cs_num = m.group(1)
        if cs_num not in screens:
            screens[cs_num] = {
                "example_key":   meta.get("example_key", ""),
                "source_folder": source_folder,
            }
    return screens


def _screenshot_path(source_folder: str) -> Path:
    return _RAW_DATASET / source_folder / "Before" / "screenshot.png"


def _default_run_name(backend_name: str, model_attr: str | None) -> str:
    if model_attr:
        m = re.search(r"/endpoints/(\d+)$", model_attr)
        return m.group(1) if m else re.sub(r"[/:]", "_", model_attr)
    return backend_name


def main():
    parser = argparse.ArgumentParser(
        description="Generate revision tasks for all unique test screens."
    )
    parser.add_argument("--backend", default="gemini",
                        choices=["gemini", "vertexai", "anthropic", "openai"])
    parser.add_argument("--model", default=None,
                        help="Override model/endpoint (optional).")
    parser.add_argument("--dataset", default=str(_TEST_DATASET), metavar="PATH",
                        help=f"Test split directory (default: {_TEST_DATASET}).")
    parser.add_argument("--tasks-per-category", type=int, default=3, metavar="N",
                        help="Tasks to generate per (screen, category) pair (default: 3).")
    parser.add_argument("--run-name", default=None, metavar="NAME",
                        help="Name for this run — used as the output filename.")
    parser.add_argument("--resume", action="store_true",
                        help="Skip (screen, category) pairs already present in the results file.")
    args = parser.parse_args()

    dataset = Path(args.dataset)
    if not dataset.exists():
        raise SystemExit(f"Dataset not found: {dataset}")

    taxonomy   = _load_taxonomy()
    backend    = get_backend(args.backend, args.model,
                             endpoint_env_var="VERTEXAI_GENERATOR_ENDPOINT_ID")
    model_attr = getattr(backend, "model", None)
    run_name   = args.run_name or _default_run_name(args.backend, model_attr)

    _RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = _RESULTS_DIR / f"{run_name}.json"

    screens = _unique_screens(dataset)
    print(f"Backend:  {args.backend}  |  Model: {model_attr or '—'}")
    print(f"Dataset:  {dataset}  ({len(screens)} unique screens, "
          f"{len(taxonomy)} categories)")
    print(f"Output:   {output_path.relative_to(_ROOT)}")
    print(f"Tasks/category: {args.tasks_per_category}")
    print()

    # Load existing results if resuming
    existing: dict[str, dict] = {}
    if args.resume and output_path.exists():
        saved = json.loads(output_path.read_text())
        existing = saved.get("screens", {})
        done = sum(
            1 for s in existing.values()
            for v in s.get("categories", {}).values()
            if v is not None
        )
        print(f"Resuming: {done} (screen, category) pairs already done.")

    results: dict[str, dict] = dict(existing)
    n_screens = len(screens)

    for i, (cs_num, info) in enumerate(
        sorted(screens.items(), key=lambda x: int(x[0])), 1
    ):
        source_folder = info["source_folder"]
        screenshot    = _screenshot_path(source_folder)

        if not screenshot.exists():
            print(f"  [{i:>2}/{n_screens}] CaseStudy-{cs_num} — screenshot missing, SKIP")
            continue

        if cs_num not in results:
            results[cs_num] = {
                "example_key":   info["example_key"],
                "source_folder": source_folder,
                "categories":    {},
            }

        img_bytes = screenshot.read_bytes()
        cats_done = results[cs_num]["categories"]

        for cat in taxonomy:
            cat_name = cat["name"]
            if cat_name in cats_done and cats_done[cat_name] is not None:
                continue  # already done (resume)

            print(f"  [{i:>2}/{n_screens}] CaseStudy-{cs_num} | {cat_name} ... ",
                  end="", flush=True)
            try:
                tasks = generate_tasks(
                    screenshot_path=screenshot,
                    backend=backend,
                    taxonomy_category=cat,
                    count=args.tasks_per_category,
                )
                cats_done[cat_name] = tasks
                print(f"done ({len(tasks)} tasks)")
            except Exception as e:
                cats_done[cat_name] = None
                print(f"ERROR: {e}")

        # Save after each screen so a partial run is always recoverable
        output_path.write_text(json.dumps({
            "run_name":           run_name,
            "backend":            args.backend,
            "model":              model_attr,
            "dataset":            str(dataset),
            "timestamp":          datetime.now(timezone.utc).isoformat(),
            "tasks_per_category": args.tasks_per_category,
            "screens":            results,
        }, indent=2))

    total = sum(
        len(s.get("categories", {})) for s in results.values()
    )
    print(f"\nDone. {len(results)} screens, {total} (screen, category) pairs.")
    print(f"Results saved to {output_path.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
