"""
Step 2 of the two-step evaluation pipeline.

Inputs per example:
  - Task.txt                      — the original revision task
  - step1_spec.txt                — expected-change spec generated by Step 1
  - Before/screenshot.png         — original interface
  - After/screenshot.png          — revised interface
  - dom_diff.txt (if cached)      — pre-computed DOM diff; computed on the fly if absent

Produces a structured PASS / PARTIAL / FAIL verdict with image-primary reasoning
and dimension-level notes.

Output: Evaluator/step2_results.json

Running:
    # Run over all Datasets/RawDataset examples (default)
    python Evaluator/step2.py

    # Run against the held-out test split
    python Evaluator/step2.py --dataset Datasets/EvaluatorModelDataset/Test

    # Run on a single example (either RawDataset or EvaluatorModelDataset layout)
    python Evaluator/step2.py --example Datasets/RawDataset/Participant_2_CaseStudy-1.1-CLAUDE
    python Evaluator/step2.py --example Datasets/EvaluatorModelDataset/Test/Example-000

    # Resume a partially completed run
    python Evaluator/step2.py --resume

    # Use the fine-tuned evaluator model on Vertex AI
    python Evaluator/step2.py --backend vertexai --dataset Datasets/EvaluatorModelDataset/Test

    # Override model string explicitly
    python Evaluator/step2.py --backend vertexai --model projects/my-proj/locations/us-central1/endpoints/123
"""

import argparse
import json
import re
import sys
from pathlib import Path

from dotenv import load_dotenv

_ROOT = Path(__file__).parent.parent
load_dotenv(_ROOT / "Util" / ".env")

sys.path.insert(0, str(_ROOT / "Util"))
from backends import Backend, get_backend

from dom_diff import dom_diff as compute_dom_diff

_DATASET = _ROOT / "Datasets" / "RawDataset"
_PROMPT_FILE = Path(__file__).parent / "step2_prompt.txt"
_OUTPUT_FILE = Path(__file__).parent / "step2_results.json"
_DEFAULT_BACKEND = "gemini"
_MODEL_SUFFIX = re.compile(r"-(CLAUDE|GEMINI|OPENAI)$")


def _resolve_paths(folder: Path) -> tuple[Path, Path, Path]:
    """Return (task_file, before_screenshot, after_screenshot) for either layout.

    RawDataset layout:         Task.txt  /  Before/screenshot.png  /  After/screenshot.png
    EvaluatorModelDataset layout:  task.txt  /  before_screenshot.png  /  after_screenshot.png
    """
    if (folder / "before_screenshot.png").exists():
        return (
            folder / "task.txt",
            folder / "before_screenshot.png",
            folder / "after_screenshot.png",
        )
    return (
        folder / "Task.txt",
        folder / "Before" / "screenshot.png",
        folder / "After" / "screenshot.png",
    )


def _get_dom_diff(folder: Path) -> str:
    """Return DOM diff text: read cached file if present, else compute on the fly."""
    cached = folder / "dom_diff.txt"
    if cached.exists():
        return cached.read_text()
    # Support both layouts for the HTML files
    before_html = folder / "before.html" if (folder / "before.html").exists() else folder / "Before" / "index.html"
    after_html  = folder / "after.html"  if (folder / "after.html").exists()  else folder / "After"  / "index.html"
    if before_html.exists() and after_html.exists():
        return compute_dom_diff(before_html, after_html)
    return "(DOM diff unavailable — HTML files not found)"


def _get_step1_spec(folder: Path) -> str:
    """Read the step 1 spec from step1_spec.txt in the example folder."""
    spec_file = folder / "step1_spec.txt"
    if spec_file.exists():
        return spec_file.read_text().strip()
    return "(Step 1 spec unavailable — run fill_step1.py)"


def _run_one(folder: Path, backend: Backend) -> dict:
    task_file, before, after = _resolve_paths(folder)
    task = task_file.read_text().strip()

    if not before.exists() or not after.exists():
        return {"error": "Missing before or after screenshot"}

    step1_spec = _get_step1_spec(folder)
    dom_diff_text = _get_dom_diff(folder)

    prompt = _PROMPT_FILE.read_text().format(
        task=task,
        step1_spec=step1_spec,
        dom_diff=dom_diff_text,
    )

    response = backend.generate(prompt, images=[before.read_bytes(), after.read_bytes()])

    # Parse verdict from first non-empty line
    verdict = None
    for line in response.splitlines():
        line = line.strip().upper()
        if line in ("PASS", "PARTIAL", "FAIL"):
            verdict = line
            break

    return {
        "task": task,
        "verdict": verdict,
        "response": response,
        "step1_key": _MODEL_SUFFIX.sub("", folder.name),
    }


def main():
    parser = argparse.ArgumentParser(
        description="Step 2: produce pass/partial/fail verdict from spec + screenshots + DOM diff."
    )
    target = parser.add_mutually_exclusive_group()
    target.add_argument("--example", metavar="PATH",
                        help="Run on a single example folder (for testing).")
    target.add_argument("--dataset", default=str(_DATASET), metavar="PATH",
                        help=f"RawDataset directory (default: {_DATASET}).")

    parser.add_argument("--backend", default=_DEFAULT_BACKEND,
                        choices=["gemini", "vertexai", "anthropic", "openai"],
                        help=f"Model backend (default: {_DEFAULT_BACKEND}). "
                             "Use 'vertexai' for the fine-tuned evaluator model "
                             "(reads VERTEXAI_EVALUATOR_ENDPOINT_ID from .env).")
    parser.add_argument("--model", default=None,
                        help="Override the model/endpoint (optional; uses backend default or env var).")
    parser.add_argument("--resume", action="store_true",
                        help="Skip examples already present in step2_results.json.")
    args = parser.parse_args()

    if args.example:
        folders = [Path(args.example)]
    else:
        folders = sorted(f for f in Path(args.dataset).iterdir() if f.is_dir())

    existing: dict = {}
    if args.resume and _OUTPUT_FILE.exists():
        existing = json.loads(_OUTPUT_FILE.read_text())
        print(f"Resuming: {len(existing)} done, {len(folders) - len(existing)} remaining")

    backend = get_backend(args.backend, args.model,
                          endpoint_env_var="VERTEXAI_EVALUATOR_ENDPOINT_ID")
    print(f"Backend: {args.backend} | Model: {backend.model if hasattr(backend, 'model') else '—'} | Examples: {len(folders)}")

    results = dict(existing)
    n = len(folders)

    for i, folder in enumerate(folders, start=1):
        if args.resume and folder.name in existing:
            continue
        print(f"  [{i}/{n}] {folder.name} ... ", end="", flush=True)
        try:
            result = _run_one(folder, backend)
            if "error" in result:
                print(f"SKIP — {result['error']}")
            else:
                print(result["verdict"])
            results[folder.name] = result
        except Exception as e:
            print(f"ERROR: {e}")
            results[folder.name] = {"error": str(e)}

        _OUTPUT_FILE.write_text(json.dumps(results, indent=2))

    print(f"\nDone. Results saved to {_OUTPUT_FILE.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
