"""
Core logic for generating UI revision tasks from a Before screenshot.

Revision tasks are generated by Gemini 2.5 Pro. The module is backend-agnostic
in the sense that it only needs a callable that accepts (prompt, images) → str,
but in practice it is always called with a GeminiBackend instance.
"""

import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from backends import Backend

_SYSTEM = (
    "You are a UI/UX product expert generating revision task specifications for "
    "software engineers. You will be shown a screenshot of a mobile or web UI and "
    "asked to generate a set of concrete revision tasks.\n\n"

    "SCOPE GUIDELINES:\n"
    "Each task should be a minor, targeted revision — roughly one incremental step "
    "above the current state of the UI (think n → n+1, not n → n+10). A good task "
    "touches one to three components. Avoid:\n"
    "  • Trivially cosmetic changes (e.g. shifting one element by a pixel).\n"
    "  • Sweeping redesigns that restructure the entire layout or replace multiple "
    "sections of the page at once.\n\n"

    "REVISION SOURCES — tasks may come from either of these motivations:\n"
    "  1. New stakeholder requirement — a product manager, designer, or client has "
    "requested a new capability or UI element that does not currently exist. These "
    "tasks may involve adding entirely new components to the screen.\n"
    "  2. Usability improvement — an existing component should be changed to better "
    "communicate information, improve accessibility, reduce friction, or align with "
    "design conventions.\n\n"

    "EACH TASK MUST CONTAIN ALL THREE OF THE FOLLOWING:\n"
    "  (a) Motivation: Why is this change needed? For a stakeholder requirement, "
    "briefly state the product or business reason. For a usability improvement, "
    "explain what is currently unclear, inaccessible, or suboptimal.\n"
    "  (b) Precise component identification: Name the specific component(s) to be "
    "changed and describe their current appearance and location in the screenshot "
    "(e.g. 'the dark blue primary action button labeled \"Continue\" in the bottom "
    "center of the screen', or 'the row of three icon buttons in the top-right "
    "corner of the navigation bar').\n"
    "  (c) Unambiguous change description: Describe exactly what the component "
    "should look like or do after the revision. Leave no room for interpretation — "
    "if a color is changing, say which color; if text is moving, say where it "
    "should end up.\n\n"

    "OUTPUT FORMAT:\n"
    "Return exactly {count} numbered tasks. Each task is a short, self-contained "
    "paragraph of two to four sentences. Use this format:\n"
    "1. <task text>\n"
    "2. <task text>\n"
    "...\n\n"
    "Do not include any preamble, section headers, or closing remarks — only the "
    "numbered list."
)


def _build_prompt(count: int) -> str:
    return _SYSTEM.format(count=count) + "\n\nGenerate the revision tasks for the UI shown in the screenshot."


def _parse_tasks(response_text: str) -> list[str]:
    """Split a numbered list response into individual task strings."""
    # Match lines starting with a digit and a period/dot, possibly after whitespace.
    pattern = re.compile(r"^\s*\d+\.\s+", re.MULTILINE)
    splits = pattern.split(response_text)
    # First split is the empty prefix before "1."
    tasks = [t.strip() for t in splits if t.strip()]
    return tasks


def generate_tasks(screenshot_path: Path, backend: "Backend", count: int = 5) -> list[str]:
    """Generate `count` revision tasks for the UI in `screenshot_path`.

    Returns a list of task strings (length may be less than `count` if the
    model produces fewer items).
    """
    prompt = _build_prompt(count)
    image_bytes = screenshot_path.read_bytes()
    response_text = backend.generate(prompt, images=[image_bytes])
    return _parse_tasks(response_text)
